# -*- coding: utf-8 -*-
"""decisionTree_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TuvH4AE5LV7ImA4HfFQPriE0AAeDod-
"""

import seaborn as sns                                # To load Titanic dataset
from sklearn.tree import DecisionTreeClassifier       # Import Decision Tree
from sklearn.model_selection import train_test_split  # For splitting data
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder        # For encoding categorical variables
import pandas as pd

# Load the Titanic dataset
df = sns.load_dataset("titanic")

# Drop rows with missing values in selected columns
df = df[["survived", "pclass", "sex", "age", "sibsp", "parch", "fare"]].dropna()

# Encode the 'sex' column (male/female to 0/1)
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])

# Split features and target
X = df.drop("survived", axis=1)
y = df["survived"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))