# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TuvH4AE5LV7ImA4HfFQPriE0AAeDod-
"""

from sklearn.datasets import load_digits             # Load built-in digits dataset
from sklearn.neighbors import KNeighborsClassifier   # KNN algorithm
from sklearn.model_selection import train_test_split # For splitting data
from sklearn.metrics import accuracy_score, classification_report

# Load the Digits dataset
digits = load_digits()
X = digits.data
y = digits.target

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the KNN model
model = KNeighborsClassifier(n_neighbors=5)  # Using 5 nearest neighbors
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

