# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TuvH4AE5LV7ImA4HfFQPriE0AAeDod-
"""

from sklearn.datasets import load_wine                 # Load wine dataset
from sklearn.ensemble import RandomForestClassifier    # Import Random Forest model
from sklearn.model_selection import train_test_split   # For splitting data
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
data = load_wine()
X = data.data        # Features (13 chemical measurements)
y = data.target      # Target (3 classes of wine)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=data.target_names))