# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TuvH4AE5LV7ImA4HfFQPriE0AAeDod-
"""

from sklearn.datasets import load_breast_cancer         # Load breast cancer dataset
from sklearn.svm import SVC                             # Support Vector Classifier
from sklearn.model_selection import train_test_split    # For splitting data
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
data = load_breast_cancer()
X = data.data        # Features (30 medical measurements)
y = data.target      # Target (0 = malignant, 1 = benign)

# Train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train SVM model
model = SVC(kernel='linear')  # Using a linear kernel
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Evaluate model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=data.target_names))